- name: start container
  docker_container:
    name: notme-pgsodium
    image: pgsodium
    state: started
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:15432"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 15s
    ports:
      - "15432:5432"
    env:
      POSTGRES_PASSWORD: "development"
      POSTGRES_USER: "postgres"
    volumes:
      - ~/data/pgsodium:/var/lib/postgresql/data
  tags:
    - db
    - container

- name: check container
  wait_for:
    host: "localhost"
    port: 15432
  register: container
  tags:
    - db
    - container
