#!/usr/bin/env python

import os
import sys

sys.path.insert(1, os.path.join(sys.path[0], "../.."))

import time  # noqa: E402

import typer  # noqa: E402

import dot_init  # noqa: E402, F401
import log  # noqa: E402
import services.graph.query  # noqa: E402
import services.graph.session  # noqa: E402
import services.graph.tx  # noqa: E402

logger = log.init("cli")

app = typer.Typer()


@app.command()
def write(
    uri: str = typer.Option(..., "--uri"),
    limit: int = typer.Option(..., "--limit"),
    count: int = typer.Option(1, "--count"),
    sleep: int = typer.Option(3, "--sleep"),
):
    with services.graph.session.get(uri=uri) as neo:
        read_query = f"match(n) with n as node return node limit {limit}"

        i = 0
        while i < count:
            logger.info(f"[{__name__}] loop {i}")

            records = services.graph.query.execute(read_query, {}, neo)

            for record in records:
                node_id = record["node"].id
                version = record["node"].get("version")

                logger.info(f"[{__name__}] record {node_id} version {version}")

                update_query = f"match(n) where id(n) = {node_id} set n.version = {version+1} return n"
                neo.write_transaction(services.graph.tx.write, update_query, {})

            i += 1

            time.sleep(sleep)


if __name__ == "__main__":
    app()
