#!/usr/bin/env python

import os
import sys

sys.path.insert(1, os.path.join(sys.path[0], "../.."))

import time  # noqa: E402

import typer  # noqa: E402

import dot_init  # noqa: E402, F401
import log  # noqa: E402
import services.graph.query  # noqa: E402
import services.graph.session  # noqa: E402

logger = log.init("cli")

app = typer.Typer()


@app.command()
def read(
    uri: str = typer.Option(..., "--uri"),
    limit: int = typer.Option(..., "--limit"),
    count: int = typer.Option(1, "--count"),
    sleep: int = typer.Option(3, "--sleep"),
):
    with services.graph.session.get(uri=uri) as neo:
        query = f"match(node) return node limit {limit}"

        i = 0
        while i < count:
            logger.info(f"[{__name__}] loop {i}")

            records = services.graph.query.execute(query, {}, neo)

            for record in records:
                logger.info(f"[{__name__}] record {record['node'].id}")

            i += 1

            time.sleep(sleep)


if __name__ == "__main__":
    app()
