- name: start kql server container
  docker_container:
    name: notme-ksql-srv
    image: confluentinc/ksqldb-server:0.27.2
    state: started
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8088 "]
      interval: 2m
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - name: notme
    ports:
      - "8088:8088"
    env:
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_BOOTSTRAP_SERVERS: "notme-redpanda:29092"
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
  tags:
    - ksqldb
    - container

- name: start kql cli container
  docker_container:
    name: notme-ksql-cli
    image: confluentinc/ksqldb-cli:0.27.2
    state: started
    networks:
      - name: notme
    entrypoint: /bin/sh
    tty: true
