apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- otel-agent-configmap.yml
- otel-deployment.yml
- otel-service.yml
# - neo4j-deploy.yml
- postgres-deploy.yml
- redpanda-deploy.yml
- typesense-deploy.yml
configMapGenerator:
- name: otel-collector-config
  files:
  - otel-collector.props.secret.yml