apiVersion: apps/v1
kind: Deployment
metadata:
  name: notme-postgres
  namespace: default
  labels:
    app: notme-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notme-postgres
  template:
    metadata:
      labels:
        app: notme-postgres
    spec:
      containers:
      - name: notme-postgres
        image: postgis/postgis:14-3.3
        imagePullPolicy: IfNotPresent
        env:
          - name: POSTGRES_PASSWORD
            value: development
          - name: POSTGRES_USER
            value: postgres
          - name: PGDATA
            value: /host-data/postgres # host file system
        ports:
          - containerPort: 5432
            protocol: TCP
        volumeMounts:
          - mountPath: /host-data
            name: host-volume
      volumes:
      - name: host-volume
        hostPath:
          path: /host-data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: notme-postgres
  name: notme-postgres
spec:
  ports:
    - port: 5433 # port exposed to external users
      protocol: TCP
      targetPort: 5432
  selector:
    app: notme-postgres
  type: NodePort
