apiVersion: apps/v1
kind: Deployment
metadata:
  name: notme-redpanda
  namespace: default
  labels:
    app: notme-redpanda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notme-redpanda
  template:
    metadata:
      labels:
        app: notme-redpanda
    spec:
      containers:
      - name: notme-redpanda
        image: notme-redpanda:1.0
        imagePullPolicy: Never # use local registry
        command: ["/bin/sh", "-c", "rpk redpanda start --overprovisioned --smp 1 --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092 --advertise-kafka-addr PLAINTEXT://notme-redpanda:9092,OUTSIDE://notme-redpanda:9092"]
        ports:
          - containerPort: 9092
            protocol: TCP
        volumeMounts:
          - mountPath: /host-data
            name: host-volume
      volumes:
      - name: host-volume
        hostPath:
          path: /host-data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: notme-redpanda
  name: notme-redpanda
spec:
  ports:
    - port: 9092 # port exposed to external users
      protocol: TCP
      targetPort: 9092
  selector:
    app: notme-redpanda
  type: NodePort
