#!/usr/bin/env python

import os
import sys

import ulid

sys.path.insert(1, os.path.join(sys.path[0], "../.."))

import prefect
import prefect.orion.schemas.states

import dot_init  # noqa: E402, F401
import log
import services.kafka
import services.tasks


@prefect.flow()
def rp_up() -> int:
    logger = prefect.get_run_logger()

    topic = services.kafka.topic_up()
    key = ulid.new().str

    logger.info(f"sending topic '{topic}' key '{key}'")

    services.tasks.rp_up_send(topic=topic, key=key)

    logger.info(f"checking topic '{topic}' key '{key}'")

    code = services.tasks.rp_up_consume(topic=topic, group="group-0", key=key)

    if code != 0:
        logger.error(f"error topic '{topic}' key '{key}' code {code}")
        return prefect.orion.schemas.states.Failed(message=f"rp_up_flow error with code {code}")

    logger.info(f"received topic '{topic}' key '{key}' code {code}")

    return code


if __name__ == "__main__":
    rp_up()
