#!/bin/sh

docker network create --driver=bridge cluster

docker run --name=notme_read_1 --detach --network=cluster \
    --publish=34474:7474 --publish=34473:7473 --publish=34687:7687 \
    --hostname=read-1 \
    --env NEO4J_dbms_mode=READ_REPLICA \
    --env NEO4J_causal__clustering_initial__discovery__members=core-1:5000,core-2:5000,core-3:5000 \
    --env NEO4J_ACCEPT_LICENSE_AGREEMENT=yes \
    --env NEO4J_dbms_connector_bolt_advertised__address=localhost:34687 \
    --env NEO4J_dbms_connector_http_advertised__address=localhost:34474 \
    --env NEO4J_dbms_routing_enabled=true \
    neo4j:4.4.8-enterprise