#!/usr/bin/env python

import os
import sys

import ulid

sys.path.insert(1, os.path.join(sys.path[0], "../.."))

import prefect
import prefect.orion.schemas.states

import dot_init  # noqa: E402, F401
import log
import services.kafka
import services.tasks

logger = log.init("cli")


@prefect.flow()
def rp_up_flow() -> int:
    logger.info(f"rp_up_flow starting")

    topic = services.kafka.topic_up()

    key = services.tasks.rp_up_send_task(topic=topic)

    logger.info(f"rp_up_flow sent key {key}")

    code = services.tasks.rp_up_consume_task(topic=topic, group="group-0", key=key)

    logger.info(f"rp_up_flow completed key {key} code {code}")

    if code != 0:
        return prefect.orion.schemas.states.Failed(message=f"rp_up_flow error with code {code}")

    return code


if __name__ == "__main__":
    rp_up_flow()
