#!/usr/bin/env python

import os
import sys

import dotinit  # noqa: F401

sys.path.insert(1, os.path.join(sys.path[0], ".."))

import db_cli_boot  # noqa: E402
import db_cli_entity  # noqa: E402
import typer  # noqa: E402

import log  # noqa: E402

logger = log.init("cli")

app = typer.Typer()
app.add_typer(db_cli_boot.app, name="boot")
app.add_typer(db_cli_entity.app, name="entity")


if __name__ == "__main__":
    app()
