#!/usr/bin/env python

import os
import sys

import typer

sys.path.insert(1, os.path.join(sys.path[0], ".."))

import db_cli_boot  # noqa: E402
import db_cli_entity  # noqa: E402

import dotinit  # noqa: E402, F401

app = typer.Typer()
app.add_typer(db_cli_boot.app, name="boot")
app.add_typer(db_cli_entity.app, name="entity")

import database  # noqa: E402

# initialize database
database.migrate()


if __name__ == "__main__":
    app()
