apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent-config
data:
  agent.yml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
    exporters:
      otlp:
        endpoint: http://opentelemetrycollector:4317
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
