---
# Source: redpanda/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: redpanda
  namespace: "default"
  labels:
    helm.sh/chart: redpanda-2.3.15
    app.kubernetes.io/name: redpanda
    app.kubernetes.io/instance: "redpanda"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/component: redpanda
data:
  bootstrap.yaml: |
    enable_sasl: false
    storage_min_free_bytes: 1073741824
  redpanda.yaml: |
    config_file: /etc/redpanda/redpanda.yaml
    redpanda:
      empty_seed_starts_cluster: false
      admin:
        name: admin
        address: 0.0.0.0
        port: 9644
      kafka_api:
        - name: internal
          address: 0.0.0.0
          port: 9093
        - name: default
          address: 0.0.0.0
          port: 9094
      kafka_api_tls:
      rpc_server:
        address: 0.0.0.0
        port: 33145
      seed_servers:
        - host:
            address: 0.0.0.0
            port: 33145
    schema_registry:
      schema_registry:
        - name: internal
          address: 0.0.0.0
          port: 8081
        - name: default
          address: 0.0.0.0
          port: 8080
      schema_registry_api_tls:
    pandaproxy:
      pandaproxy_api:
        - name: internal
          address: 0.0.0.0
          port: 8082
        - name: default
          address: 0.0.0.0
          port: 8083
      pandaproxy_api_tls:
    rpk:
      enable_usage_stats: true
      overprovisioned: false
      enable_memory_locking: false
