#!/usr/bin/env python

import datetime
import os
import sys

sys.path.insert(1, os.path.join(sys.path[0], "../.."))

import typer  # noqa: E402

import dot_init  # noqa: E402, F401
import log  # noqa: E402
import models  # noqa: E402
import typesearch  # noqa: E402

logger = log.init("cli")

app = typer.Typer()


@app.command()
def index():
    client = typesearch.client_default()

    collections = client.collections.retrieve()

    logger.info(
        {
            "message": "typesense_stats",
            "uri": typesearch.client_default_uri(),
            "collections": len(collections),
        }
    )

    for collection in collections:
        logger.info(
            {
                "message": "typesense_stats",
                "uri": typesearch.client_default_uri(),
                "collection": collection["name"],
                "docs": collection["num_documents"],
            }
        )


if __name__ == "__main__":
    app()
