#!/usr/bin/env python

import os
import sys

sys.path.insert(1, os.path.join(sys.path[0], "../.."))

import typer  # noqa: E402

import dot_init  # noqa: E402, F401
import log  # noqa: E402
import models  # noqa: E402
import typesearch  # noqa: E402

logger = log.init("cli")

app = typer.Typer()


@app.command()
def create():
    client = typesearch.client_default()

    collections = client.collections.retrieve()
    names = [collection["name"] for collection in collections]

    if models.User.typesense_collection() in names:
        client.collections[models.User.typesense_collection()].delete()

    client.collections.create(models.User.typesense_schema())


if __name__ == "__main__":
    app()
