#!/usr/bin/env python

import datetime
import os
import sys

sys.path.insert(1, os.path.join(sys.path[0], "../.."))

import sqlmodel  # noqa: E402
import typer  # noqa: E402
from sqlmodel.sql.expression import Select, SelectOfScalar  # noqa: E402

import dot_init  # noqa: E402, F401
import log  # noqa: E402
import models  # noqa: E402
import services.database.session  # noqa: E402
import typesearch  # noqa: E402

# this disables the warning: SAWarning: Class SelectOfScalar will not make use of SQL compilation caching
SelectOfScalar.inherit_cache = True  # type: ignore
Select.inherit_cache = True  # type: ignore

logger = log.init("cli")

app = typer.Typer()


@app.command()
def index():
    client = typesearch.client_default()

    collection_name = models.User.typesense_collection()

    with services.database.session.get() as db:
        users_query = sqlmodel.select(models.User)

        users = db.exec(users_query).all()

        for user in users:
            if user.exported_at:
                client.collections[collection_name].documents[user.id].update(user.typesense_document)
            else:
                client.collections[collection_name].documents.create(user.typesense_document)

            user.exported_at = datetime.datetime.now(datetime.UTC)
            db.add(user)
            db.commit()


if __name__ == "__main__":
    app()
