#!/bin/sh

# add core members to running cluster

docker run --name=notme-core-4 --detach --network=cluster \
    --publish=34474:7474 --publish=34473:7473 --publish=34687:7687 \
    --hostname=core-4 \
    --env NEO4J_dbms_mode=CORE \
    --env NEO4J_causal__clustering_expected__core__cluster__size=3 \
    --env NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime=3 \
    --env NEO4J_causal__clustering_initial__discovery__members=core-1:5000,core-2:5000,core-3:5000 \
    --env NEO4J_ACCEPT_LICENSE_AGREEMENT=yes \
    --env NEO4J_dbms_connector_bolt_advertised__address=localhost:34687 \
    --env NEO4J_dbms_connector_http_advertised__address=localhost:34474 \
    --env NEO4J_dbms_routing_enabled=true \
    --env NEO4J_AUTH=neo4j/development \
    neo4j:4.4.8-enterprise

docker run --name=notme-core-5 --detach --network=cluster \
    --publish=35474:7474 --publish=35473:7473 --publish=35687:7687 \
    --hostname=core-5 \
    --env NEO4J_dbms_mode=CORE \
    --env NEO4J_causal__clustering_expected__core__cluster__size=3 \
    --env NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime=3 \
    --env NEO4J_causal__clustering_initial__discovery__members=core-1:5000,core-2:5000,core-3:5000 \
    --env NEO4J_ACCEPT_LICENSE_AGREEMENT=yes \
    --env NEO4J_dbms_connector_bolt_advertised__address=localhost:35687 \
    --env NEO4J_dbms_connector_http_advertised__address=localhost:35474 \
    --env NEO4J_dbms_routing_enabled=true \
    --env NEO4J_AUTH=neo4j/development \
    neo4j:4.4.8-enterprise
