#!/bin/sh

usage()
{
  echo "Usage: $0 [-n namespace]"
  exit 2
}

while getopts n:?h flag
do
    case "${flag}" in
        n) ns=${OPTARG};;
        h|?) usage ;;
    esac
done

sudo kubefwd svc --context minikube -n $ns