- name: check core cluster
  shell: "nc -zv localhost 31687"
  register: core
  tags:
    - neo
    - services

- name: start core cluster
  script: ./neo4j_cluster_core_init
  when: core.rc != 0

- name: check read replica
  shell: "nc -zv localhost 34687"
  register: reader
  tags:
    - neo
    - services

- name: start read replica
  script: ./neo4j_cluster_reader_init
  when: reader.rc != 0

- name: verify cluster
  wait_for:
    host: "localhost"
    port: 31687
  register: core
  tags:
    - neo
    - services

- name: create default databases
  shell: "cypher-shell -a neo4j://127.0.0.1:31687 -u neo4j -p development 'create database {{item}} if not exists;'"
  loop:
    - "notme.dev"
    - "notme.tst"
  retries: 12
  delay: 5
  register: result
  until: result.rc == 0
  tags:
    - neo
    - services
