# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chess_pb2 as chess__pb2


class StreamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.message = channel.stream_stream(
                '/stream.Stream/message',
                request_serializer=chess__pb2.Message.SerializeToString,
                response_deserializer=chess__pb2.Message.FromString,
                )


class StreamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def message(self, request_iterator, context):
        """A Bidirectional streaming RPC.

        Accepts a stream of Message sent while a route is being traversed,
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'message': grpc.stream_stream_rpc_method_handler(
                    servicer.message,
                    request_deserializer=chess__pb2.Message.FromString,
                    response_serializer=chess__pb2.Message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stream.Stream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Stream(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def message(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/stream.Stream/message',
            chess__pb2.Message.SerializeToString,
            chess__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
