# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\nuser.proto\x12\tprotoblog"#\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\tb\x06proto3'
)


_USER = DESCRIPTOR.message_types_by_name["User"]
User = _reflection.GeneratedProtocolMessageType(
    "User",
    (_message.Message,),
    {
        "DESCRIPTOR": _USER,
        "__module__": "user_pb2"
        # @@protoc_insertion_point(class_scope:protoblog.User)
    },
)
_sym_db.RegisterMessage(User)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _USER._serialized_start = 25
    _USER._serialized_end = 60
# @@protoc_insertion_point(module_scope)
