#!/usr/bin/env python

from dotenv import load_dotenv

load_dotenv()

import json
import os
import sys
import typer

from sqlalchemy import func
from sqlmodel import select, Session, SQLModel

sys.path.insert(1, os.path.join(sys.path[0], ".."))

import database
import log
import models
import services.entities

logger = log.init("cli")

app = typer.Typer()
entity_app = typer.Typer()
app.add_typer(entity_app, name="entity")

# initialize database
database.migrate(database.engine)


@entity_app.command("count")
def entity_count():
    with Session(database.engine) as db:
        count = db.exec(select([func.count(models.Entity.id)])).one()

    logger.info(f"[db-cli] entity_count {count}")


@entity_app.command("list")
def entity_list(query: str = typer.Option("", "--query", "-q")):
    with Session(database.engine) as db:
        struct_list = services.entities.List(db, query, 0, 1000).call()

        logger.info(f"[db-cli] entity_list {struct_list.count}")

        for entity in struct_list.objects:
            logger.info(f"[db-cli] {entity.pack()}")


if __name__ == "__main__":
    app()
