#!/usr/bin/env python

from dotenv import load_dotenv

load_dotenv()

import os
import sys

import zerorpc

sys.path.insert(1, os.path.join(sys.path[0], ".."))

import log
import services.zero.rpc

logger = log.init("cli")


def rpc_server(port: int = 4242):
    logger.info(f"rpc_server port {port} starting")

    s = zerorpc.Server(services.zero.rpc.User())
    s.bind(f"tcp://0.0.0.0:{port}")
    s.run()


if __name__ == "__main__":
    rpc_server()
