#!/bin/sh

echo "starting redpanda"
eval "docker-compose -p notme -f docker-compose-redpanda.yml up -d"

echo "starting neo4j"
eval "docker-compose -p notme -f docker-compose-neo4j.yml up -d"

echo "completed"

