#!/bin/sh

docker network create --driver=bridge cluster

docker run --name=notme_core1 --detach --network=cluster \
    --publish=13474:7474 --publish=13473:7473 --publish=13687:7687 \
    --hostname=core1 \
    --env NEO4J_dbms_mode=CORE \
    --env NEO4J_causal__clustering_expected__core__cluster__size=3 \
    --env NEO4J_causal__clustering_initial__discovery__members=core1:5000,core2:5000,core3:5000 \
    --env NEO4J_ACCEPT_LICENSE_AGREEMENT=yes \
    --env NEO4J_dbms_connector_bolt_advertised__address=localhost:13687 \
    --env NEO4J_dbms_connector_http_advertised__address=localhost:13474 \
    --env NEO4J_AUTH=neo4j/development \
    neo4j:4.4.8-enterprise

docker run --name=notme_core2 --detach --network=cluster \
    --publish=14474:7474 --publish=14473:7473 --publish=14687:7687 \
    --hostname=core2 \
    --env NEO4J_dbms_mode=CORE \
    --env NEO4J_causal__clustering_expected__core__cluster__size=3 \
    --env NEO4J_causal__clustering_initial__discovery__members=core1:5000,core2:5000,core3:5000 \
    --env NEO4J_ACCEPT_LICENSE_AGREEMENT=yes \
    --env NEO4J_dbms_connector_bolt_advertised__address=localhost:14687 \
    --env NEO4J_dbms_connector_http_advertised__address=localhost:14474 \
    --env NEO4J_AUTH=neo4j/development \
    neo4j:4.4.8-enterprise

docker run --name=notme_core3 --detach --network=cluster \
    --publish=15474:7474 --publish=15473:7473 --publish=15687:7687 \
    --hostname=core3 \
    --env NEO4J_dbms_mode=CORE \
    --env NEO4J_causal__clustering_expected__core__cluster__size=3 \
    --env NEO4J_causal__clustering_initial__discovery__members=core1:5000,core2:5000,core3:5000 \
    --env NEO4J_ACCEPT_LICENSE_AGREEMENT=yes \
    --env NEO4J_dbms_connector_bolt_advertised__address=localhost:15687 \
    --env NEO4J_dbms_connector_http_advertised__address=localhost:15474 \
    --env NEO4J_AUTH=neo4j/development \
    neo4j:4.4.8-enterprise

docker run --name=notme_read1 --detach --network=cluster \
    --publish=17474:7474 --publish=17473:7473 --publish=17687:7687 \
    --hostname=read1 \
    --env NEO4J_dbms_mode=READ_REPLICA \
    --env NEO4J_causal__clustering_initial__discovery__members=core1:5000,core2:5000,core3:5000 \
    --env NEO4J_ACCEPT_LICENSE_AGREEMENT=yes \
    --env NEO4J_dbms_connector_bolt_advertised__address=localhost:17687 \
    --env NEO4J_dbms_connector_http_advertised__address=localhost:17474 \
    neo4j:4.4.8-enterprise