#!/usr/bin/env python

import os
import sys
import time

sys.path.insert(1, os.path.join(sys.path[0], ".."))

import dot_init  # noqa: E402, F401
import kafka  # noqa: E402
import neo  # noqa: E402
import services.graph  # noqa: E402

while True:
    # check services
    kafka.service_check()
    neo.service_check()
    services.graph.service_check()

    time.sleep(30)
