#!/bin/sh

docker network create --driver=bridge cluster

docker run --name=notme_core_1 --detach --network=cluster \
    --publish=31474:7474 --publish=31473:7473 --publish=31687:7687 \
    --hostname=core-1 \
    --env NEO4J_dbms_mode=CORE \
    --env NEO4J_causal__clustering_expected__core__cluster__size=3 \
    --env NEO4J_causal__clustering_initial__discovery__members=core-1:5000,core-2:5000,core-3:5000 \
    --env NEO4J_ACCEPT_LICENSE_AGREEMENT=yes \
    --env NEO4J_dbms_connector_bolt_advertised__address=localhost:31687 \
    --env NEO4J_dbms_connector_http_advertised__address=localhost:31474 \
    --env NEO4J_dbms_routing_enabled=true \
    --env NEO4J_AUTH=neo4j/development \
    neo4j:4.4.8-enterprise

docker run --name=notme_core_2 --detach --network=cluster \
    --publish=32474:7474 --publish=32473:7473 --publish=32687:7687 \
    --hostname=core-2 \
    --env NEO4J_dbms_mode=CORE \
    --env NEO4J_causal__clustering_expected__core__cluster__size=3 \
    --env NEO4J_causal__clustering_initial__discovery__members=core-1:5000,core-2:5000,core-3:5000 \
    --env NEO4J_ACCEPT_LICENSE_AGREEMENT=yes \
    --env NEO4J_dbms_connector_bolt_advertised__address=localhost:32687 \
    --env NEO4J_dbms_connector_http_advertised__address=localhost:32474 \
    --env NEO4J_dbms_routing_enabled=true \
    --env NEO4J_AUTH=neo4j/development \
    neo4j:4.4.8-enterprise

docker run --name=notme_core_3 --detach --network=cluster \
    --publish=33474:7474 --publish=33473:7473 --publish=33687:7687 \
    --hostname=core-3 \
    --env NEO4J_dbms_mode=CORE \
    --env NEO4J_causal__clustering_expected__core__cluster__size=3 \
    --env NEO4J_causal__clustering_initial__discovery__members=core-1:5000,core-2:5000,core-3:5000 \
    --env NEO4J_ACCEPT_LICENSE_AGREEMENT=yes \
    --env NEO4J_dbms_connector_bolt_advertised__address=localhost:33687 \
    --env NEO4J_dbms_connector_http_advertised__address=localhost:33474 \
    --env NEO4J_dbms_routing_enabled=true \
    --env NEO4J_AUTH=neo4j/development \
    neo4j:4.4.8-enterprise
